//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace citPOINT.StrategyApp.ViewModel {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("citPOINT.StrategyApp.ViewModel.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date range must be less that or equal {0} and greater than or equal {1}.
        /// </summary>
        public static string DateRange {
            get {
                return ResourceManager.GetString("DateRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date must be greater than or equal {0}..
        /// </summary>
        public static string DateRangeEnd {
            get {
                return ResourceManager.GetString("DateRangeEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date must be less than or equal {0}..
        /// </summary>
        public static string DateRangeStart {
            get {
                return ResourceManager.GetString("DateRangeStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date must be greater  than start date..
        /// </summary>
        public static string InValidDateRange {
            get {
                return ResourceManager.GetString("InValidDateRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strategy type required.
        /// </summary>
        public static string MustFillStrategyType {
            get {
                return ResourceManager.GetString("MustFillStrategyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be greater than zero..
        /// </summary>
        public static string PositiveValue {
            get {
                return ResourceManager.GetString("PositiveValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your offer fits to the strategy..
        /// </summary>
        public static string StategyStatusFits {
            get {
                return ResourceManager.GetString("StategyStatusFits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your offer not fits to the strategy..
        /// </summary>
        public static string StategyStatusNotFits {
            get {
                return ResourceManager.GetString("StategyStatusNotFits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please {0} the total rate of the offer to be {1}..
        /// </summary>
        public static string StrategyAdvice {
            get {
                return ResourceManager.GetString("StrategyAdvice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please be sure that you have rated your offers in Preference App..
        /// </summary>
        public static string StrategyAdviceDefault {
            get {
                return ResourceManager.GetString("StrategyAdviceDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No advice needed..
        /// </summary>
        public static string StrategyNoAdvice {
            get {
                return ResourceManager.GetString("StrategyNoAdvice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t calculate Strategy Status..
        /// </summary>
        public static string StrategyStutasDefault {
            get {
                return ResourceManager.GetString("StrategyStutasDefault", resourceCulture);
            }
        }
    }
}
