//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("StrategyAppModel", "FK__Conversat__Negot__09DE7BCC", "NegotiationStrategySettings", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(citPOINT.StrategyApp.Data.Web.NegotiationStrategySetting), "ConversationStrategySettings", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(citPOINT.StrategyApp.Data.Web.ConversationStrategySetting), true)]
[assembly: EdmRelationshipAttribute("StrategyAppModel", "FK__Conversat__Strat__08EA5793", "StrategyType", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(citPOINT.StrategyApp.Data.Web.StrategyType), "ConversationStrategySettings", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(citPOINT.StrategyApp.Data.Web.ConversationStrategySetting), true)]
[assembly: EdmRelationshipAttribute("StrategyAppModel", "FK__Negotiati__Strat__0AD2A005", "StrategyType", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(citPOINT.StrategyApp.Data.Web.StrategyType), "NegotiationStrategySettings", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(citPOINT.StrategyApp.Data.Web.NegotiationStrategySetting), true)]

#endregion

namespace citPOINT.StrategyApp.Data.Web
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class StrategyAppEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new StrategyAppEntities object using the connection string found in the 'StrategyAppEntities' section of the application configuration file.
        /// </summary>
        public StrategyAppEntities() : base("name=StrategyAppEntities", "StrategyAppEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new StrategyAppEntities object.
        /// </summary>
        public StrategyAppEntities(string connectionString) : base(connectionString, "StrategyAppEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new StrategyAppEntities object.
        /// </summary>
        public StrategyAppEntities(EntityConnection connection) : base(connection, "StrategyAppEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ConversationStrategySetting> ConversationStrategySettings
        {
            get
            {
                if ((_ConversationStrategySettings == null))
                {
                    _ConversationStrategySettings = base.CreateObjectSet<ConversationStrategySetting>("ConversationStrategySettings");
                }
                return _ConversationStrategySettings;
            }
        }
        private ObjectSet<ConversationStrategySetting> _ConversationStrategySettings;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<NegotiationStrategySetting> NegotiationStrategySettings
        {
            get
            {
                if ((_NegotiationStrategySettings == null))
                {
                    _NegotiationStrategySettings = base.CreateObjectSet<NegotiationStrategySetting>("NegotiationStrategySettings");
                }
                return _NegotiationStrategySettings;
            }
        }
        private ObjectSet<NegotiationStrategySetting> _NegotiationStrategySettings;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<StrategyType> StrategyTypes
        {
            get
            {
                if ((_StrategyTypes == null))
                {
                    _StrategyTypes = base.CreateObjectSet<StrategyType>("StrategyTypes");
                }
                return _StrategyTypes;
            }
        }
        private ObjectSet<StrategyType> _StrategyTypes;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ConversationStrategySettings EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToConversationStrategySettings(ConversationStrategySetting conversationStrategySetting)
        {
            base.AddObject("ConversationStrategySettings", conversationStrategySetting);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the NegotiationStrategySettings EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToNegotiationStrategySettings(NegotiationStrategySetting negotiationStrategySetting)
        {
            base.AddObject("NegotiationStrategySettings", negotiationStrategySetting);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the StrategyTypes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToStrategyTypes(StrategyType strategyType)
        {
            base.AddObject("StrategyTypes", strategyType);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="StrategyAppModel", Name="ConversationStrategySetting")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ConversationStrategySetting : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ConversationStrategySetting object.
        /// </summary>
        /// <param name="conversationStrategySettingsID">Initial value of the ConversationStrategySettingsID property.</param>
        /// <param name="conversationID">Initial value of the ConversationID property.</param>
        /// <param name="startDate">Initial value of the StartDate property.</param>
        /// <param name="endDate">Initial value of the EndDate property.</param>
        /// <param name="strategyTypeID">Initial value of the StrategyTypeID property.</param>
        public static ConversationStrategySetting CreateConversationStrategySetting(global::System.Guid conversationStrategySettingsID, global::System.Guid conversationID, global::System.DateTime startDate, global::System.DateTime endDate, global::System.Int32 strategyTypeID)
        {
            ConversationStrategySetting conversationStrategySetting = new ConversationStrategySetting();
            conversationStrategySetting.ConversationStrategySettingsID = conversationStrategySettingsID;
            conversationStrategySetting.ConversationID = conversationID;
            conversationStrategySetting.StartDate = startDate;
            conversationStrategySetting.EndDate = endDate;
            conversationStrategySetting.StrategyTypeID = strategyTypeID;
            return conversationStrategySetting;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid ConversationStrategySettingsID
        {
            get
            {
                return _ConversationStrategySettingsID;
            }
            set
            {
                if (_ConversationStrategySettingsID != value)
                {
                    OnConversationStrategySettingsIDChanging(value);
                    ReportPropertyChanging("ConversationStrategySettingsID");
                    _ConversationStrategySettingsID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ConversationStrategySettingsID");
                    OnConversationStrategySettingsIDChanged();
                }
            }
        }
        private global::System.Guid _ConversationStrategySettingsID;
        partial void OnConversationStrategySettingsIDChanging(global::System.Guid value);
        partial void OnConversationStrategySettingsIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid ConversationID
        {
            get
            {
                return _ConversationID;
            }
            set
            {
                OnConversationIDChanging(value);
                ReportPropertyChanging("ConversationID");
                _ConversationID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ConversationID");
                OnConversationIDChanged();
            }
        }
        private global::System.Guid _ConversationID;
        partial void OnConversationIDChanging(global::System.Guid value);
        partial void OnConversationIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime StartDate
        {
            get
            {
                return _StartDate;
            }
            set
            {
                OnStartDateChanging(value);
                ReportPropertyChanging("StartDate");
                _StartDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("StartDate");
                OnStartDateChanged();
            }
        }
        private global::System.DateTime _StartDate;
        partial void OnStartDateChanging(global::System.DateTime value);
        partial void OnStartDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime EndDate
        {
            get
            {
                return _EndDate;
            }
            set
            {
                OnEndDateChanging(value);
                ReportPropertyChanging("EndDate");
                _EndDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EndDate");
                OnEndDateChanged();
            }
        }
        private global::System.DateTime _EndDate;
        partial void OnEndDateChanging(global::System.DateTime value);
        partial void OnEndDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> BetaValue
        {
            get
            {
                return _BetaValue;
            }
            set
            {
                OnBetaValueChanging(value);
                ReportPropertyChanging("BetaValue");
                _BetaValue = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BetaValue");
                OnBetaValueChanged();
            }
        }
        private Nullable<global::System.Decimal> _BetaValue;
        partial void OnBetaValueChanging(Nullable<global::System.Decimal> value);
        partial void OnBetaValueChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 StrategyTypeID
        {
            get
            {
                return _StrategyTypeID;
            }
            set
            {
                OnStrategyTypeIDChanging(value);
                ReportPropertyChanging("StrategyTypeID");
                _StrategyTypeID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("StrategyTypeID");
                OnStrategyTypeIDChanged();
            }
        }
        private global::System.Int32 _StrategyTypeID;
        partial void OnStrategyTypeIDChanging(global::System.Int32 value);
        partial void OnStrategyTypeIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> NegotiationStrategySettingsID
        {
            get
            {
                return _NegotiationStrategySettingsID;
            }
            set
            {
                OnNegotiationStrategySettingsIDChanging(value);
                ReportPropertyChanging("NegotiationStrategySettingsID");
                _NegotiationStrategySettingsID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NegotiationStrategySettingsID");
                OnNegotiationStrategySettingsIDChanged();
            }
        }
        private Nullable<global::System.Guid> _NegotiationStrategySettingsID;
        partial void OnNegotiationStrategySettingsIDChanging(Nullable<global::System.Guid> value);
        partial void OnNegotiationStrategySettingsIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> Deleted
        {
            get
            {
                return _Deleted;
            }
            set
            {
                OnDeletedChanging(value);
                ReportPropertyChanging("Deleted");
                _Deleted = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Deleted");
                OnDeletedChanged();
            }
        }
        private Nullable<global::System.Boolean> _Deleted;
        partial void OnDeletedChanging(Nullable<global::System.Boolean> value);
        partial void OnDeletedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> DeletedBy
        {
            get
            {
                return _DeletedBy;
            }
            set
            {
                OnDeletedByChanging(value);
                ReportPropertyChanging("DeletedBy");
                _DeletedBy = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DeletedBy");
                OnDeletedByChanged();
            }
        }
        private Nullable<global::System.Guid> _DeletedBy;
        partial void OnDeletedByChanging(Nullable<global::System.Guid> value);
        partial void OnDeletedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DeletedOn
        {
            get
            {
                return _DeletedOn;
            }
            set
            {
                OnDeletedOnChanging(value);
                ReportPropertyChanging("DeletedOn");
                _DeletedOn = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DeletedOn");
                OnDeletedOnChanged();
            }
        }
        private Nullable<global::System.DateTime> _DeletedOn;
        partial void OnDeletedOnChanging(Nullable<global::System.DateTime> value);
        partial void OnDeletedOnChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("StrategyAppModel", "FK__Conversat__Negot__09DE7BCC", "NegotiationStrategySettings")]
        public NegotiationStrategySetting NegotiationStrategySetting
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<NegotiationStrategySetting>("StrategyAppModel.FK__Conversat__Negot__09DE7BCC", "NegotiationStrategySettings").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<NegotiationStrategySetting>("StrategyAppModel.FK__Conversat__Negot__09DE7BCC", "NegotiationStrategySettings").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<NegotiationStrategySetting> NegotiationStrategySettingReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<NegotiationStrategySetting>("StrategyAppModel.FK__Conversat__Negot__09DE7BCC", "NegotiationStrategySettings");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<NegotiationStrategySetting>("StrategyAppModel.FK__Conversat__Negot__09DE7BCC", "NegotiationStrategySettings", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("StrategyAppModel", "FK__Conversat__Strat__08EA5793", "StrategyType")]
        public StrategyType StrategyType
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<StrategyType>("StrategyAppModel.FK__Conversat__Strat__08EA5793", "StrategyType").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<StrategyType>("StrategyAppModel.FK__Conversat__Strat__08EA5793", "StrategyType").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<StrategyType> StrategyTypeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<StrategyType>("StrategyAppModel.FK__Conversat__Strat__08EA5793", "StrategyType");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<StrategyType>("StrategyAppModel.FK__Conversat__Strat__08EA5793", "StrategyType", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="StrategyAppModel", Name="NegotiationStrategySetting")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class NegotiationStrategySetting : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new NegotiationStrategySetting object.
        /// </summary>
        /// <param name="negotiationStrategySettingsID">Initial value of the NegotiationStrategySettingsID property.</param>
        /// <param name="negotiationID">Initial value of the NegotiationID property.</param>
        /// <param name="defaultStartDate">Initial value of the DefaultStartDate property.</param>
        /// <param name="defaultEndDate">Initial value of the DefaultEndDate property.</param>
        /// <param name="strategyTypeID">Initial value of the StrategyTypeID property.</param>
        public static NegotiationStrategySetting CreateNegotiationStrategySetting(global::System.Guid negotiationStrategySettingsID, global::System.Guid negotiationID, global::System.DateTime defaultStartDate, global::System.DateTime defaultEndDate, global::System.Int32 strategyTypeID)
        {
            NegotiationStrategySetting negotiationStrategySetting = new NegotiationStrategySetting();
            negotiationStrategySetting.NegotiationStrategySettingsID = negotiationStrategySettingsID;
            negotiationStrategySetting.NegotiationID = negotiationID;
            negotiationStrategySetting.DefaultStartDate = defaultStartDate;
            negotiationStrategySetting.DefaultEndDate = defaultEndDate;
            negotiationStrategySetting.StrategyTypeID = strategyTypeID;
            return negotiationStrategySetting;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid NegotiationStrategySettingsID
        {
            get
            {
                return _NegotiationStrategySettingsID;
            }
            set
            {
                if (_NegotiationStrategySettingsID != value)
                {
                    OnNegotiationStrategySettingsIDChanging(value);
                    ReportPropertyChanging("NegotiationStrategySettingsID");
                    _NegotiationStrategySettingsID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("NegotiationStrategySettingsID");
                    OnNegotiationStrategySettingsIDChanged();
                }
            }
        }
        private global::System.Guid _NegotiationStrategySettingsID;
        partial void OnNegotiationStrategySettingsIDChanging(global::System.Guid value);
        partial void OnNegotiationStrategySettingsIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid NegotiationID
        {
            get
            {
                return _NegotiationID;
            }
            set
            {
                OnNegotiationIDChanging(value);
                ReportPropertyChanging("NegotiationID");
                _NegotiationID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NegotiationID");
                OnNegotiationIDChanged();
            }
        }
        private global::System.Guid _NegotiationID;
        partial void OnNegotiationIDChanging(global::System.Guid value);
        partial void OnNegotiationIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DefaultStartDate
        {
            get
            {
                return _DefaultStartDate;
            }
            set
            {
                OnDefaultStartDateChanging(value);
                ReportPropertyChanging("DefaultStartDate");
                _DefaultStartDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DefaultStartDate");
                OnDefaultStartDateChanged();
            }
        }
        private global::System.DateTime _DefaultStartDate;
        partial void OnDefaultStartDateChanging(global::System.DateTime value);
        partial void OnDefaultStartDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DefaultEndDate
        {
            get
            {
                return _DefaultEndDate;
            }
            set
            {
                OnDefaultEndDateChanging(value);
                ReportPropertyChanging("DefaultEndDate");
                _DefaultEndDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DefaultEndDate");
                OnDefaultEndDateChanged();
            }
        }
        private global::System.DateTime _DefaultEndDate;
        partial void OnDefaultEndDateChanging(global::System.DateTime value);
        partial void OnDefaultEndDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> BetaValue
        {
            get
            {
                return _BetaValue;
            }
            set
            {
                OnBetaValueChanging(value);
                ReportPropertyChanging("BetaValue");
                _BetaValue = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BetaValue");
                OnBetaValueChanged();
            }
        }
        private Nullable<global::System.Decimal> _BetaValue;
        partial void OnBetaValueChanging(Nullable<global::System.Decimal> value);
        partial void OnBetaValueChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 StrategyTypeID
        {
            get
            {
                return _StrategyTypeID;
            }
            set
            {
                OnStrategyTypeIDChanging(value);
                ReportPropertyChanging("StrategyTypeID");
                _StrategyTypeID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("StrategyTypeID");
                OnStrategyTypeIDChanged();
            }
        }
        private global::System.Int32 _StrategyTypeID;
        partial void OnStrategyTypeIDChanging(global::System.Int32 value);
        partial void OnStrategyTypeIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> Deleted
        {
            get
            {
                return _Deleted;
            }
            set
            {
                OnDeletedChanging(value);
                ReportPropertyChanging("Deleted");
                _Deleted = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Deleted");
                OnDeletedChanged();
            }
        }
        private Nullable<global::System.Boolean> _Deleted;
        partial void OnDeletedChanging(Nullable<global::System.Boolean> value);
        partial void OnDeletedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> DeletedBy
        {
            get
            {
                return _DeletedBy;
            }
            set
            {
                OnDeletedByChanging(value);
                ReportPropertyChanging("DeletedBy");
                _DeletedBy = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DeletedBy");
                OnDeletedByChanged();
            }
        }
        private Nullable<global::System.Guid> _DeletedBy;
        partial void OnDeletedByChanging(Nullable<global::System.Guid> value);
        partial void OnDeletedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DeletedOn
        {
            get
            {
                return _DeletedOn;
            }
            set
            {
                OnDeletedOnChanging(value);
                ReportPropertyChanging("DeletedOn");
                _DeletedOn = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DeletedOn");
                OnDeletedOnChanged();
            }
        }
        private Nullable<global::System.DateTime> _DeletedOn;
        partial void OnDeletedOnChanging(Nullable<global::System.DateTime> value);
        partial void OnDeletedOnChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("StrategyAppModel", "FK__Conversat__Negot__09DE7BCC", "ConversationStrategySettings")]
        public EntityCollection<ConversationStrategySetting> ConversationStrategySettings
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ConversationStrategySetting>("StrategyAppModel.FK__Conversat__Negot__09DE7BCC", "ConversationStrategySettings");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ConversationStrategySetting>("StrategyAppModel.FK__Conversat__Negot__09DE7BCC", "ConversationStrategySettings", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("StrategyAppModel", "FK__Negotiati__Strat__0AD2A005", "StrategyType")]
        public StrategyType StrategyType
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<StrategyType>("StrategyAppModel.FK__Negotiati__Strat__0AD2A005", "StrategyType").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<StrategyType>("StrategyAppModel.FK__Negotiati__Strat__0AD2A005", "StrategyType").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<StrategyType> StrategyTypeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<StrategyType>("StrategyAppModel.FK__Negotiati__Strat__0AD2A005", "StrategyType");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<StrategyType>("StrategyAppModel.FK__Negotiati__Strat__0AD2A005", "StrategyType", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="StrategyAppModel", Name="StrategyType")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class StrategyType : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new StrategyType object.
        /// </summary>
        /// <param name="strategyTypeID">Initial value of the StrategyTypeID property.</param>
        /// <param name="strategyTypeName">Initial value of the StrategyTypeName property.</param>
        public static StrategyType CreateStrategyType(global::System.Int32 strategyTypeID, global::System.String strategyTypeName)
        {
            StrategyType strategyType = new StrategyType();
            strategyType.StrategyTypeID = strategyTypeID;
            strategyType.StrategyTypeName = strategyTypeName;
            return strategyType;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 StrategyTypeID
        {
            get
            {
                return _StrategyTypeID;
            }
            set
            {
                if (_StrategyTypeID != value)
                {
                    OnStrategyTypeIDChanging(value);
                    ReportPropertyChanging("StrategyTypeID");
                    _StrategyTypeID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("StrategyTypeID");
                    OnStrategyTypeIDChanged();
                }
            }
        }
        private global::System.Int32 _StrategyTypeID;
        partial void OnStrategyTypeIDChanging(global::System.Int32 value);
        partial void OnStrategyTypeIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String StrategyTypeName
        {
            get
            {
                return _StrategyTypeName;
            }
            set
            {
                OnStrategyTypeNameChanging(value);
                ReportPropertyChanging("StrategyTypeName");
                _StrategyTypeName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("StrategyTypeName");
                OnStrategyTypeNameChanged();
            }
        }
        private global::System.String _StrategyTypeName;
        partial void OnStrategyTypeNameChanging(global::System.String value);
        partial void OnStrategyTypeNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Beta
        {
            get
            {
                return _Beta;
            }
            set
            {
                OnBetaChanging(value);
                ReportPropertyChanging("Beta");
                _Beta = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Beta");
                OnBetaChanged();
            }
        }
        private Nullable<global::System.Decimal> _Beta;
        partial void OnBetaChanging(Nullable<global::System.Decimal> value);
        partial void OnBetaChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("StrategyAppModel", "FK__Conversat__Strat__08EA5793", "ConversationStrategySettings")]
        public EntityCollection<ConversationStrategySetting> ConversationStrategySettings
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ConversationStrategySetting>("StrategyAppModel.FK__Conversat__Strat__08EA5793", "ConversationStrategySettings");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ConversationStrategySetting>("StrategyAppModel.FK__Conversat__Strat__08EA5793", "ConversationStrategySettings", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("StrategyAppModel", "FK__Negotiati__Strat__0AD2A005", "NegotiationStrategySettings")]
        public EntityCollection<NegotiationStrategySetting> NegotiationStrategySettings
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<NegotiationStrategySetting>("StrategyAppModel.FK__Negotiati__Strat__0AD2A005", "NegotiationStrategySettings");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<NegotiationStrategySetting>("StrategyAppModel.FK__Negotiati__Strat__0AD2A005", "NegotiationStrategySettings", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
